name: S3 Deploy
on: [push]
jobs:
 build-deploy-stage:
    uses: ./.github/workflows/reuseworkflow.yml
    with:
     environment: stage
 build-deploy-prod:
    uses: ./.github/workflows/reuseworkflow.yml
    with:
     environment: prod

