name: Example workflow for S3 Deploy
on: [push]
jobs:
   build-and-deploy-stage: 
    environment: stage
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v1

        - name: Check Variables
          run: echo "${{ vars.S3_BUCKET }}"

 
            
   build-and-deploy-prod: 
    environment: prod
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v1

        - name: Check Variables
          run: echo "${{ vars.S3_BUCKET }}"

            



